### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by hedgieinsocks** [tiagomelo/go-clipboard#1]
Hi, the example from the readme results in `github.com/tiagomelo/go-clipboard: no non-test Go files in /home/hedgieinsocks/go/pkg/mod/github.com/tiagomelo/go-clipboard@v0.1.0` error. 

The module was installed via `go get github.com/tiagomelo/go-clipboard`.  

I'm not a pro go dev, so dunno whether I did something wrong. But I kinda expected it to work out-of-the-box ;P

**Comment by tiagomelo** [comment]
hey @hedgieinsocks !

first of all, thanks for visiting the repo!

so I just did it in a fresh notebook:

in a fresh project,

```
$ go get github.com/tiagomelo/go-clipboard
go: downloading github.com/tiagomelo/go-clipboard v0.1.0
go: added github.com/tiagomelo/go-clipboard v0.1.0
```

then, used it:

```
package main

import (
	"fmt"
	"os"

	"github.com/tiagomelo/go-clipboard/clipboard"
)

func main() {
	text := "some text"
	c := clipboard.New()
	if err := c.CopyText(text); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	fmt.Printf("text \"%s\" was copied into clipboard. Paste it elsewhere.\n", text)
}

```

having this output:

```
$ go run main.go 
text "some text" was copied into clipboard. Paste it elsewhere.
```

**Comment by tiagomelo** [comment]
let me know if I can assist you with anything!

**Comment by hedgieinsocks** [comment]
Thank you for your response! Your example imported via `"github.com/tiagomelo/go-clipboard/clipboard"` and it did work! But the import from the readme goes like `clipboard "github.com/tiagomelo/go-clipboard"` and errors out for me. Perhaps readme is wrong or outdated. But anyway, many thanks again, it works as you suggested :D

**Comment by tiagomelo** [comment]
ah I see what is the problem, I've forgot to update the import path on README.md, which should be `github.com/tiagomelo/go-clipboard/clipboard`. Thanks very much for pointing that out, just fixed it in README.md!
